import React from 'react';
import { optionsOf } from '../../utils/surveyModel';

export default function SurveyFields({ definition, answers, onChange, disabled = false }) {
    const field = 'w-full rounded-2xl border border-tossGrey200 bg-white px-4 py-3.5 text-sm font-medium text-tossGrey900 outline-none transition focus:border-haifnRed focus:ring-4 focus:ring-[#CF3A27]/10 disabled:bg-tossGrey50';
    return <div className="space-y-9">{definition.questions.map((q, index) => <fieldset key={q.id} disabled={disabled} className="space-y-3">
        <legend className="mb-3 text-[15px] font-black leading-6 text-tossGrey900"><span className="mr-2 text-haifnRed">{String(index + 1).padStart(2, '0')}</span>{q.title} {q.required && <span className="text-haifnRed" aria-label="필수">*</span>}</legend>
        {['short', 'text'].includes(q.type) ? (q.type === 'text'
            ? <textarea aria-label={q.title} className={field} rows={4} maxLength={q.maxLength || 5000} placeholder={q.placeholder || ''} value={answers[q.id] || ''} onChange={e => onChange(q.id, e.target.value)} />
            : <input aria-label={q.title} className={field} maxLength={q.maxLength || 5000} placeholder={q.placeholder || ''} value={answers[q.id] || ''} onChange={e => onChange(q.id, e.target.value)} />)
            : q.type === 'star' ? <div className="grid grid-cols-5 gap-1.5" role="group" aria-label={q.title}>{[1, 2, 3, 4, 5].map(n => <button type="button" key={n} aria-pressed={answers[q.id] === n} aria-label={`${n}점`} onClick={() => onChange(q.id, n)} className={`rounded-xl border px-1 py-3 text-sm font-bold transition ${answers[q.id] === n ? 'border-haifnRed bg-haifnRed text-white' : 'border-tossGrey200 bg-white text-tossGrey600 hover:border-[#E7B7AD] hover:bg-[#FFF9F7]'}`}>★ {n}</button>)}{!q.required && <button type="button" className="col-span-5 text-sm font-bold text-tossGrey500" onClick={() => onChange(q.id, null)}>선택 취소</button>}</div>
                : <div className="space-y-2.5">{optionsOf(q).map((option, optionIndex) => { const selected = q.type === 'multiple' ? (answers[q.id] || []).includes(option) : answers[q.id] === option; return <label key={option} className={`flex cursor-pointer items-center gap-3 rounded-2xl border p-4 text-sm font-semibold transition ${selected ? 'border-haifnRed bg-[#FFF8F6] text-tossGrey900 ring-1 ring-haifnRed' : 'border-tossGrey200 bg-white text-tossGrey700 hover:border-[#E7B7AD]'}`}><input className="h-4 w-4 accent-[#CF3A27]" type={q.type === 'multiple' ? 'checkbox' : 'radio'} name={`survey-${q.id}`} checked={selected} onChange={() => onChange(q.id, q.type === 'multiple' ? (selected ? answers[q.id].filter(v => v !== option) : [...(answers[q.id] || []), option]) : option)} />{q.optionDetails?.[optionIndex]?.emoji && <span className="text-lg">{q.optionDetails[optionIndex].emoji}</span>}<span>{option}</span></label>; })}{!q.required && q.type === 'choice' && answers[q.id] != null && <button type="button" className="text-sm font-bold text-tossGrey500" onClick={() => onChange(q.id, null)}>선택 취소</button>}</div>}
    </fieldset>)}</div>;
}
