import React, { useState } from 'react';
import { ArrowDown, ArrowUp, Check, Copy, ListChecks, MessageSquareText, Plus, Repeat2, Save, Sparkles, Star, Trash2, Type } from 'lucide-react';
import { newQuestion, QUESTION_TYPES, validateDefinition } from '../../utils/surveyModel';

const TYPE_ICONS = { short: Type, text: MessageSquareText, choice: Check, multiple: ListChecks, star: Star };

// Keep the multi-question editor visually aligned with the legacy survey editor.
export default function SurveyDefinitionEditor({ initial, onSave, onCancel, busy, allowTemplate = false, compact = false, connections = [] }) {
    const [value, setValue] = useState(initial || { title: '', description: '', questions: [newQuestion()] });
    const [saveAsTemplate, setSaveAsTemplate] = useState(false);
    const [linkPolicies, setLinkPolicies] = useState(() => Object.fromEntries(connections.map(link => [link.id, { frequency: link.frequency || 'EVERY_VISIT', is_default: !!link.is_default }])));
    const [error, setError] = useState('');
    const update = (id, patch) => setValue(current => ({ ...current, questions: current.questions.map(question => question.id === id ? { ...question, ...patch } : question) }));
    const move = (index, direction) => setValue(current => { const questions = [...current.questions]; [questions[index], questions[index + direction]] = [questions[index + direction], questions[index]]; return { ...current, questions }; });
    const addQuestion = () => setValue(current => { const questions = [...current.questions]; const additionalIndex = questions.findIndex(question => question.role === 'additional_comment'); questions.splice(additionalIndex < 0 ? questions.length : additionalIndex, 0, newQuestion()); return { ...current, questions }; });
    const duplicate = question => setValue(current => ({ ...current, questions: [...current.questions, { ...question, id: newQuestion().id, title: `${question.title} 복사본` }] }));
    const remove = id => setValue(current => ({ ...current, questions: current.questions.filter(question => question.id !== id) }));
    const updateOption = (question, index, text) => update(question.id, { options: (question.options || []).map((option, optionIndex) => optionIndex === index ? text : option) });
    const updateOptionDetail = (question, index, patch) => update(question.id, { optionDetails: (question.options || []).map((_, optionIndex) => ({ ...(question.optionDetails?.[optionIndex] || {}), ...(optionIndex === index ? patch : {}) })) });
    const additionalQuestion = value.questions.find(question => question.role === 'additional_comment');
    const toggleAdditionalComment = () => setValue(current => {
        const existing = current.questions.find(question => question.role === 'additional_comment');
        return { ...current, questions: existing
            ? current.questions.filter(question => question.id !== existing.id)
            : [...current.questions, { ...newQuestion(), title: '추가 의견이 있다면 적어주세요', type: 'text', required: false, role: 'additional_comment', placeholder: '선택한 이유나 의견을 자유롭게 알려주세요.', maxLength: 300 }] };
    });
    const field = 'w-full rounded-xl border border-gray-200 bg-slate-50 px-4 py-3 text-sm outline-none transition focus:border-blue-500 focus:bg-white';

    const save = async event => {
        event.preventDefault();
        const clean = { ...value, title: value.title.trim(), description: (value.description || '').trim(), questions: value.questions.map(question => ({ ...question, title: question.title.trim(), options: (question.options || []).map(option => String(option).trim()).filter(Boolean), optionDetails: ['choice','multiple'].includes(question.type) ? (question.options || []).map((_, index) => question.optionDetails?.[index] || {}) : undefined })) };
        const message = validateDefinition(clean);
        if (message) return setError(message);
        setError('');
        try { await onSave(clean, { saveAsTemplate, linkPolicies }); } catch (saveError) { setError(saveError.message); }
    };

    return <div className={`space-y-7 rounded-[24px] border border-[#f2f4f6] bg-white p-5 ${compact ? '' : 'shadow-sm md:p-7'}`}>
        <div className="flex flex-col justify-between gap-3 border-b border-gray-100 pb-5 md:flex-row md:items-center"><div><p className="text-xs font-bold text-blue-600">{compact ? '프로그램 설문' : '통합 설문'}</p><h2 className="mt-1 text-xl font-bold text-gray-900">{initial ? '설문 편집' : '새 설문 만들기'}</h2><p className="mt-1 text-sm text-gray-500">질문을 추가하고 순서와 응답 유형을 설정합니다.</p></div><button type="button" onClick={onCancel} className="self-start rounded-xl px-3 py-2 text-sm font-bold text-gray-500 hover:bg-gray-50">취소</button></div>

        {allowTemplate && <label className="flex cursor-pointer items-center justify-between rounded-2xl border border-violet-100 bg-violet-50 p-4"><span><strong className="block text-sm text-violet-900">설문 템플릿으로 저장</strong><span className="mt-1 block text-xs font-medium text-violet-600">프로그램을 만들 때 질문 구성을 불러와 사용할 수 있습니다.</span></span><input type="checkbox" checked={saveAsTemplate} onChange={event => setSaveAsTemplate(event.target.checked)} className="h-5 w-5 rounded border-violet-300 text-violet-600" /></label>}

        <div><label className="mb-2 block text-sm font-bold text-gray-800">설문 제목</label><input aria-label="설문 제목" className={field} value={value.title} placeholder="예: 센터 이용 만족도 조사" onChange={event => setValue({ ...value, title: event.target.value })} /><p className="mt-1.5 text-xs font-medium text-gray-400">설문 목록과 응답 결과의 제목으로 사용됩니다.</p></div>
        <div><label className="mb-2 block text-sm font-bold text-gray-800">설문 설명 <span className="font-medium text-gray-400">(선택)</span></label><textarea aria-label="설문 설명" rows={2} maxLength={300} className={`${field} resize-none`} value={value.description || ''} placeholder="응답 화면에 보여줄 안내 문구를 입력해 주세요" onChange={event => setValue({ ...value, description: event.target.value })} /><p className="mt-1.5 text-right text-xs font-medium text-gray-400">{(value.description || '').length}/300자</p></div>

        <div className="space-y-4 border-t border-gray-100 pt-6"><div className="flex items-center justify-between gap-3"><div><h3 className="font-bold text-gray-900">질문 구성</h3><p className="mt-1 text-xs text-gray-500">질문별로 응답 유형과 필수 여부를 설정합니다.</p></div><button type="button" onClick={addQuestion} className="inline-flex items-center gap-1 rounded-xl border border-blue-200 bg-blue-50 px-3 py-2 text-xs font-bold text-blue-600 hover:bg-blue-100"><Plus size={14} />질문 추가</button></div>
            {value.questions.filter(question => question.role !== 'additional_comment').map((question, index) => <section key={question.id} className="space-y-5 rounded-2xl border border-gray-200 bg-slate-50/70 p-4 md:p-5">
                <div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2"><span className="rounded-lg bg-blue-600 px-2.5 py-1 text-xs font-black text-white">Q{index + 1}</span><strong className="text-sm text-gray-800">질문 {index + 1}</strong></div><div className="flex items-center gap-1"><button type="button" aria-label="질문 위로" disabled={!index} onClick={() => move(index, -1)} className="rounded-lg p-2 text-gray-500 hover:bg-white disabled:opacity-25"><ArrowUp size={16} /></button><button type="button" aria-label="질문 아래로" disabled={index === value.questions.filter(item => item.role !== 'additional_comment').length - 1} onClick={() => move(index, 1)} className="rounded-lg p-2 text-gray-500 hover:bg-white disabled:opacity-25"><ArrowDown size={16} /></button><button type="button" aria-label="질문 복제" onClick={() => duplicate(question)} className="rounded-lg p-2 text-gray-500 hover:bg-white"><Copy size={16} /></button><button type="button" aria-label="질문 삭제" disabled={value.questions.filter(item => item.role !== 'additional_comment').length === 1} onClick={() => remove(question.id)} className="rounded-lg p-2 text-red-500 hover:bg-red-50 disabled:text-gray-300"><Trash2 size={16} /></button></div></div>
                <div><label className="mb-2 block text-xs font-bold text-gray-600">질문 내용</label><input aria-label={`질문 ${index + 1} 내용`} className={field} value={question.title} placeholder="질문을 입력하세요" onChange={event => update(question.id, { title: event.target.value })} /></div>
                <div><p className="mb-2 text-xs font-bold text-gray-600">응답 유형</p><div className="grid grid-cols-2 gap-2 sm:grid-cols-5">{Object.entries(QUESTION_TYPES).map(([type, label]) => { const Icon = TYPE_ICONS[type]; const active = question.type === type; return <button key={type} type="button" onClick={() => update(question.id, { type, metric: null, options: ['choice','multiple'].includes(type) && !(question.options || []).length ? ['선택지 1','선택지 2'] : question.options || [] })} className={`flex min-h-[74px] flex-col items-center justify-center gap-1.5 rounded-xl border px-2 py-3 text-xs font-bold transition-colors ${active ? 'border-blue-500 bg-blue-50 text-blue-700 ring-2 ring-blue-500/10' : 'border-gray-200 bg-white text-gray-500 hover:bg-gray-50'}`}><Icon size={17} />{label}</button>; })}</div></div>
                {['choice', 'multiple'].includes(question.type) && <div className="space-y-3"><div className="flex items-center justify-between"><p className="text-xs font-bold text-gray-600">선택지</p><button type="button" onClick={() => update(question.id, { options: [...(question.options || []), `선택지 ${(question.options || []).length + 1}`], optionDetails: [...(question.optionDetails || []), {}] })} className="inline-flex items-center gap-1 rounded-lg px-2 py-1.5 text-xs font-bold text-blue-600 hover:bg-blue-50"><Plus size={13} />선택지 추가</button></div>{(question.options || []).map((option, optionIndex) => <div key={optionIndex} className="space-y-2 rounded-xl border border-gray-200 bg-white p-3"><div className="flex items-center gap-2"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-gray-50 text-xs font-bold text-gray-400">{optionIndex + 1}</span><input aria-label={`질문 ${index + 1} 선택지 ${optionIndex + 1}`} className={`${field} bg-white`} value={option} onChange={event => updateOption(question, optionIndex, event.target.value)} /><button type="button" aria-label="선택지 삭제" disabled={(question.options || []).length <= 2} onClick={() => update(question.id, { options: question.options.filter((_, itemIndex) => itemIndex !== optionIndex), optionDetails: (question.optionDetails || []).filter((_, itemIndex) => itemIndex !== optionIndex) })} className="rounded-lg p-2 text-gray-400 hover:bg-red-50 hover:text-red-500 disabled:opacity-25"><Trash2 size={16} /></button></div>{question.recommendationsEnabled && <div className="grid gap-2 pl-0 sm:grid-cols-[64px_1fr_1fr] sm:pl-9"><input aria-label={`${option} 추천 이모지`} className="rounded-xl border border-gray-200 px-2 py-2 text-center" value={question.optionDetails?.[optionIndex]?.emoji || ''} placeholder="✨" onChange={event => updateOptionDetail(question, optionIndex, { emoji: event.target.value })} /><input aria-label={`${option} 추천 제목`} className="rounded-xl border border-gray-200 px-3 py-2 text-sm font-bold" value={question.optionDetails?.[optionIndex]?.title || ''} placeholder="추천 제목" onChange={event => updateOptionDetail(question, optionIndex, { title: event.target.value })} /><input aria-label={`${option} 추천 설명`} className="rounded-xl border border-gray-200 px-3 py-2 text-sm" value={question.optionDetails?.[optionIndex]?.text || ''} placeholder="추천 설명" onChange={event => updateOptionDetail(question, optionIndex, { text: event.target.value })} /></div>}</div>)}</div>}
                {['choice', 'multiple'].includes(question.type) && <label className="flex cursor-pointer items-center justify-between rounded-xl border border-amber-100 bg-amber-50/70 p-4"><span className="flex items-start gap-2"><Sparkles size={17} className="mt-0.5 text-amber-500" /><span><strong className="block text-sm text-gray-900">응답 후 콘텐츠 추천</strong><span className="mt-1 block text-xs font-medium text-gray-500">선택한 답변에 맞는 콘텐츠를 완료 전에 보여줍니다.</span></span></span><input type="checkbox" checked={!!question.recommendationsEnabled} onChange={event => update(question.id, { recommendationsEnabled: event.target.checked })} className="h-5 w-5 rounded border-amber-300 text-blue-600" /></label>}
                <div className="flex flex-col gap-3 border-t border-gray-200 pt-4 sm:flex-row sm:items-center sm:justify-between"><label className="flex cursor-pointer items-center gap-2 text-sm font-bold text-gray-700"><input type="checkbox" checked={!!question.required} onChange={event => update(question.id, { required: event.target.checked })} className="h-4 w-4 rounded border-gray-300 text-blue-600" />필수 답변</label>{question.type === 'star' && <label className="flex cursor-pointer items-center gap-2 text-sm font-bold text-gray-700"><input type="checkbox" checked={question.metric === 'satisfaction'} onChange={event => update(question.id, { metric: event.target.checked ? 'satisfaction' : null })} className="h-4 w-4 rounded border-gray-300 text-blue-600" />대표 만족도 문항</label>}</div>
            </section>)}
        </div>
        <section className="space-y-4 border-t border-gray-100 pt-6"><label className="flex cursor-pointer items-center justify-between rounded-2xl bg-gray-50 p-4"><span><strong className="block text-sm text-gray-900">추가 의견 받기</strong><span className="mt-1 block text-xs text-gray-500">설문의 마지막에 자유 입력란을 표시합니다.</span></span><input type="checkbox" checked={!!additionalQuestion} onChange={toggleAdditionalComment} className="h-5 w-5 rounded border-gray-300 text-blue-600" /></label>{additionalQuestion && <div className="grid gap-3 rounded-2xl border border-gray-200 p-4 md:grid-cols-2"><label className="text-xs font-bold text-gray-600">입력란 제목<input className={`${field} mt-2 bg-white`} value={additionalQuestion.title} onChange={event => update(additionalQuestion.id, { title: event.target.value })} /></label><label className="text-xs font-bold text-gray-600">안내 문구<input className={`${field} mt-2 bg-white`} value={additionalQuestion.placeholder || ''} onChange={event => update(additionalQuestion.id, { placeholder: event.target.value })} /></label><label className="flex items-center gap-2 text-xs font-bold text-gray-600"><input type="checkbox" checked={!!additionalQuestion.required} onChange={event => update(additionalQuestion.id, { required: event.target.checked })} className="h-4 w-4 rounded border-gray-300 text-blue-600" />필수 입력</label><label className="flex items-center justify-end gap-2 text-xs font-bold text-gray-600">최대 글자 수<input type="number" min="50" max="5000" value={additionalQuestion.maxLength || 300} onChange={event => update(additionalQuestion.id, { maxLength: Math.min(5000, Math.max(50, Number(event.target.value) || 300)) })} className="w-24 rounded-lg border border-gray-200 bg-white px-2 py-2 text-center" /></label></div>}</section>
        {!!connections.length && <section className="space-y-4 border-t border-gray-100 pt-6"><div><p className="flex items-center gap-2 text-sm font-bold text-gray-900"><Repeat2 size={17} className="text-blue-600" />현재 입실·퇴실 응답 설정</p><p className="mt-1 text-xs text-gray-500">연결은 목록에서 선택하고, 연결별 응답 주기와 기본 설문 여부만 여기서 설정합니다.</p></div>{connections.map(link => { const policy = linkPolicies[link.id] || {}; return <div key={link.id} className="grid items-center gap-3 rounded-2xl bg-gray-50 p-4 md:grid-cols-[1fr_220px_160px]"><strong className="text-sm text-gray-800">{link.displayLabel}</strong><select value={policy.frequency || 'EVERY_VISIT'} onChange={event => setLinkPolicies(current => ({ ...current, [link.id]: { ...current[link.id], frequency: event.target.value } }))} className={field}><option value="EVERY_VISIT">방문마다</option><option value="ONCE">이용자당 1회</option></select><label className="flex items-center gap-2 text-sm font-bold text-gray-700"><input type="checkbox" checked={!!policy.is_default} onChange={event => setLinkPolicies(current => ({ ...current, [link.id]: { ...current[link.id], is_default: event.target.checked } }))} className="h-5 w-5 rounded border-gray-300 text-blue-600" />기본 설문</label></div>; })}</section>}
        {error && <p role="alert" className="rounded-xl bg-red-50 px-4 py-3 text-sm font-bold text-red-600">{error}</p>}
        <div className="flex justify-end gap-2 border-t border-gray-100 pt-5"><button type="button" disabled={busy} onClick={onCancel} className="rounded-xl border border-gray-200 bg-white px-4 py-3 text-sm font-bold text-gray-600 hover:bg-gray-50">취소</button><button type="button" onClick={save} disabled={busy} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-5 py-3 text-sm font-bold text-white shadow-sm hover:bg-blue-700 disabled:opacity-50"><Save size={16} />{busy ? '저장 중…' : compact ? '질문 적용' : '설문 저장'}</button></div>
    </div>;
}
