import React, { useState } from 'react';
import { ArrowLeft, EyeOff, Printer, RotateCcw, Star, Users } from 'lucide-react';
import { optionsOf } from '../../utils/surveyModel';
import { summarizeSurveyEntries } from '../../utils/unifiedSurveySummary';
import PrintableSurveyResponse from './PrintableSurveyResponse';

const hasAnswer = value => value != null && value !== '' && (!Array.isArray(value) || value.length > 0);
const textValue = value => Array.isArray(value) ? value.join(', ') : String(value ?? '');

function ResultCard({ group, number }) {
    const { question, count } = group;
    const options = question.type === 'star' ? [5,4,3,2,1] : optionsOf(question);
    return <section className="rounded-[24px] border border-gray-100 bg-white p-5 shadow-sm sm:p-6">
        <div className="mb-5 flex flex-wrap items-start justify-between gap-3 border-b border-gray-100 pb-4"><div><p className="text-xs font-black text-blue-600">Q{String(number).padStart(2, '0')} · {question.type === 'star' ? '평점' : ['choice','multiple'].includes(question.type) ? '선택형' : '주관식'}</p><h3 className="mt-1 text-lg font-black leading-7 text-gray-900">{question.title}</h3></div><span className="rounded-lg bg-gray-50 px-3 py-1.5 text-xs font-bold text-gray-600">응답 {count.toLocaleString()}건</span></div>
        {['short','text'].includes(question.type) ? <div className="grid gap-3 md:grid-cols-2">{group.texts.map((answer,index) => <article key={index} className="rounded-xl bg-gray-50 p-4"><p className="whitespace-pre-wrap text-sm font-medium leading-6 text-gray-800">{answer.value}</p><p className="mt-3 text-xs font-bold text-gray-400">{answer.name}</p></article>)}</div> : <>{question.type === 'star' && <p className="mb-4 flex items-center gap-1 text-sm font-bold text-amber-500"><Star size={16} fill="currentColor" />평균 {count ? (group.sum / count).toFixed(1) : '—'} / 5</p>}<div className="divide-y divide-gray-100">{options.map(option => { const amount = question.type === 'star' ? (group.stars[option] || 0) : (group.choices[String(option).trim().replace(/\s+/g, ' ')] || 0); const percent = count ? Math.round(amount / count * 100) : 0; return <div key={option} className="py-3 first:pt-0 last:pb-0"><div className="mb-2 flex items-start justify-between gap-4 text-sm"><span className="font-bold leading-6 text-gray-800">{question.type === 'star' ? `${option}점` : option}</span><span className="shrink-0 font-bold tabular-nums text-gray-600">{amount.toLocaleString()}명 · {percent}%</span></div><div className="h-2 overflow-hidden rounded-full bg-gray-100"><div className={`h-full rounded-full ${question.type === 'star' ? 'bg-amber-400' : 'bg-blue-600'}`} style={{ width: `${percent}%` }} /></div></div>; })}</div>{question.type === 'multiple' && <p className="mt-4 text-xs font-medium text-gray-400">복수 선택 문항은 비율 합계가 100%를 넘을 수 있습니다.</p>}</>}
    </section>;
}

export default function UnifiedSurveyResults({ form, entries, formLinks, label, filter, setFilter, versionFilter, setVersionFilter, showExcluded, setShowExcluded, busy, onBack, onToggleExclude }) {
    const [printEntry, setPrintEntry] = useState(null);
    const filtered = entries.filter(entry => (filter === 'ALL' || entry.link_id === filter) && (versionFilter === 'ALL' || entry.version_id === versionFilter));
    const included = filtered.filter(entry => !entry.aggregation_excluded);
    const displayed = filtered.filter(entry => showExcluded ? entry.aggregation_excluded : !entry.aggregation_excluded);
    const excludedCount = filtered.length - included.length;
    const groups = summarizeSurveyEntries(included);
    const filterItems = [{ id: 'ALL', name: '전체' }, ...(entries.some(entry => entry.legacy) ? [{ id: 'LEGACY', name: '이전 응답' }] : []), ...formLinks.map(link => ({ id: link.id, name: label(link) }))];
    // The list, result header, filters, and charts all show the same
    // aggregation-included response set. Excluded rows remain available
    // through the separate excluded-response control.
    const countFor = id => entries.filter(entry => !entry.aggregation_excluded && (id === 'ALL' || entry.link_id === id)).length;
    return <div className="space-y-6">
        <section className="flex flex-col justify-between gap-4 rounded-[24px] border border-gray-100 bg-white p-5 shadow-sm md:flex-row md:items-center"><div className="flex items-center gap-3"><button onClick={onBack} className="rounded-xl border border-gray-200 bg-white p-2.5 text-gray-600 hover:bg-gray-50" title="설문 목록으로"><ArrowLeft size={18} /></button><div><p className="text-xs font-bold text-blue-600">설문 결과</p><h2 className="mt-0.5 text-xl font-black text-gray-900">{form.title}</h2></div></div><div className="flex flex-wrap items-center gap-3"><span className="flex items-center gap-2 text-sm font-bold text-gray-600"><Users size={17} />집계 {included.length}건</span><button type="button" onClick={() => setShowExcluded(current => !current)} className={`rounded-xl border px-3 py-2 text-xs font-bold ${showExcluded ? 'border-blue-600 bg-blue-600 text-white' : 'border-gray-200 bg-white text-gray-600 hover:bg-gray-50'}`}>{showExcluded ? '집계 응답 보기' : `제외된 응답 보기 (${excludedCount})`}</button></div></section>
        <section className="space-y-3 rounded-[24px] border border-gray-100 bg-white p-4 shadow-sm"><div className="flex flex-wrap gap-2">{filterItems.map(item => <button key={item.id} onClick={() => setFilter(item.id)} className={`rounded-xl px-4 py-2.5 text-sm font-bold ${filter === item.id ? 'bg-gray-900 text-white' : 'bg-gray-50 text-gray-600 hover:bg-gray-100'}`}>{item.name} <span className={filter === item.id ? 'text-white/70' : 'text-gray-400'}>{countFor(item.id)}건</span></button>)}</div>{form.survey_versions.length > 1 && <select className="w-full max-w-md rounded-xl border border-gray-200 bg-slate-50 px-3 py-2.5 text-sm font-bold outline-none focus:border-blue-500" aria-label="응답 버전 필터" value={versionFilter} onChange={event => setVersionFilter(event.target.value)}><option value="ALL">모든 질문 버전</option>{form.survey_versions.map(version => <option key={version.id} value={version.id}>{new Date(version.created_at).toLocaleString('ko-KR')} · {version.definition.title}</option>)}</select>}</section>
        <div className="space-y-4">{groups.map((group, index) => <ResultCard key={group.key} group={group} number={index + 1} />)}{!groups.length && included.length > 0 && <p className="rounded-[24px] border border-gray-100 bg-white p-8 text-center text-sm text-gray-400 shadow-sm">통계로 표시할 수 있는 응답이 없습니다. 개별 응답은 아래에서 확인할 수 있습니다.</p>}</div>
        <section className="overflow-x-auto rounded-[24px] border border-gray-100 bg-white shadow-sm"><table className="w-full min-w-[960px] text-sm"><thead className="bg-gray-50 text-gray-500"><tr><th className="px-5 py-4 text-left">응답자</th><th className="px-5 py-4 text-left">응답 내용</th><th className="px-5 py-4 text-left">적용 대상</th><th className="px-5 py-4 text-left">응답 일시</th><th className="px-5 py-4 text-left">관리</th></tr></thead><tbody>{displayed.map(entry => <tr key={entry.id} className={`border-t border-gray-100 ${entry.aggregation_excluded ? 'bg-gray-50 text-gray-400' : ''}`}><td className="px-5 py-4 align-top font-bold">{entry.users?.name || '응답자'}<span className="mt-1 block text-xs font-medium text-gray-400">{entry.users?.school || ''}</span></td><td className="max-w-xl px-5 py-4 align-top"><div className="space-y-2">{(entry.snapshot?.questions || []).filter(question => hasAnswer(entry.answers?.[question.id])).map(question => <div key={question.id}><span className="text-xs font-bold text-gray-400">{question.title}</span><p className="mt-0.5 whitespace-pre-wrap font-medium text-gray-800">{question.type === 'star' ? `${textValue(entry.answers[question.id])} / 5` : textValue(entry.answers[question.id])}</p></div>)}</div></td><td className="px-5 py-4 align-top whitespace-nowrap">{entry.legacy ? '이전 설문' : label(formLinks.find(link => link.id === entry.link_id) || { id: entry.link_id })}</td><td className="px-5 py-4 align-top whitespace-nowrap">{new Date(entry.created_at).toLocaleString('ko-KR')}</td><td className="px-5 py-4 align-top"><div className="flex flex-col items-start gap-2"><button type="button" onClick={() => setPrintEntry(entry)} className="inline-flex items-center gap-1 rounded-lg border border-blue-200 bg-blue-50 px-2.5 py-1.5 text-xs font-bold text-blue-700 hover:bg-blue-100"><Printer size={13} />인쇄</button>{entry.legacy ? <span className="text-xs text-gray-400">원본 보존</span> : <button disabled={busy} onClick={() => onToggleExclude(entry)} className={`inline-flex items-center gap-1 rounded-lg border px-2.5 py-1.5 text-xs font-bold disabled:opacity-50 ${entry.aggregation_excluded ? 'border-blue-200 bg-blue-50 text-blue-700' : 'border-gray-200 bg-white text-gray-600 hover:bg-gray-50'}`}>{entry.aggregation_excluded ? <><RotateCcw size={13} />다시 포함</> : <><EyeOff size={13} />집계 제외</>}</button>}</div></td></tr>)}</tbody></table>{!displayed.length && <p className="p-10 text-center text-sm text-gray-400">{showExcluded ? '제외된 응답이 없습니다.' : '표시할 응답이 없습니다.'}</p>}</section>
        {printEntry && <PrintableSurveyResponse entry={printEntry} onClose={() => setPrintEntry(null)} />}
    </div>;
}
