CREATE TABLE IF NOT EXISTS public.push_devices (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    device_id text NOT NULL CHECK (length(device_id) BETWEEN 16 AND 128),
    provider text NOT NULL CHECK (provider IN ('FCM', 'WEB_PUSH')),
    credential jsonb NOT NULL,
    browser text NOT NULL DEFAULT 'unknown',
    platform text NOT NULL DEFAULT 'unknown',
    display_mode text NOT NULL DEFAULT 'browser' CHECK (display_mode IN ('browser', 'standalone')),
    enabled boolean NOT NULL DEFAULT true,
    last_seen_at timestamptz NOT NULL DEFAULT now(),
    last_success_at timestamptz,
    failure_count integer NOT NULL DEFAULT 0 CHECK (failure_count >= 0),
    last_failure_code text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (user_id, device_id)
);

CREATE INDEX IF NOT EXISTS push_devices_active_user_idx
    ON public.push_devices (user_id) WHERE enabled = true;

ALTER TABLE public.push_devices ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.push_devices FROM anon, authenticated;

COMMENT ON TABLE public.push_devices IS
    'Private per-device push registry. Credentials are accessible only through verified Edge Functions.';

-- Preserve every legacy token before clients begin registering named devices.
-- Plain tokens and the short-lived JSON-array transition format are both read.
INSERT INTO public.push_devices (user_id, device_id, provider, credential, browser, platform)
SELECT source.user_id,
       'legacy_' || substr(md5(source.token), 1, 32),
       'FCM', jsonb_build_object('token', source.token), 'legacy', 'unknown'
FROM (
    SELECT u.id AS user_id, jsonb_array_elements_text(
        CASE WHEN left(trim(u.fcm_token), 1) = '['
             THEN u.fcm_token::jsonb ELSE jsonb_build_array(u.fcm_token) END
    ) AS token
    FROM public.users u
    WHERE nullif(trim(u.fcm_token), '') IS NOT NULL
) AS source
ON CONFLICT (user_id, device_id) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.push_delivery_attempts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_id uuid REFERENCES public.app_notifications(id) ON DELETE SET NULL,
    device_id uuid NOT NULL REFERENCES public.push_devices(id) ON DELETE CASCADE,
    provider text NOT NULL CHECK (provider IN ('FCM', 'WEB_PUSH')),
    accepted boolean NOT NULL,
    response_code text,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS push_delivery_attempts_device_created_idx
    ON public.push_delivery_attempts (device_id, created_at DESC);

ALTER TABLE public.push_delivery_attempts ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.push_delivery_attempts FROM anon, authenticated;
